# Generated by Django 5.2.10 on 2026-01-17 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "person_number",
                    models.IntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(help_text="Face embedding vector as JSON array"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
                "ordering": ["person_number"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "image_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonPhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_photos",
                        to="api.person",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_photos",
                        to="api.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Photo",
                "verbose_name_plural": "Person Photos",
                "ordering": ["-created_at"],
                "unique_together": {("person", "photo")},
            },
        ),
    ]
