# Generated by Django 5.2.10 on 2026-01-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('person_number',), name='unique_person_number'),
        ),
        migrations.AddConstraint(
            model_name='personphoto',
            constraint=models.UniqueConstraint(fields=('person', 'photo'), name='unique_person_photo'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('image_hash',), name='unique_image_hash'),
        ),
    ]
