# Generated by Django 5.2.10 on 2026-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_person_unique_person_number_and_more"),
    ]

    operations = [
        # Person fields already exist in database, skipping AddField operations
        # Only creating DailyStatistics table
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Date in YYYY-MM-DD format",
                        unique=True,
                    ),
                ),
                (
                    "photos_uploaded",
                    models.IntegerField(
                        default=0, help_text="Total photos uploaded on this date"
                    ),
                ),
                (
                    "faces_detected",
                    models.IntegerField(
                        default=0, help_text="Total faces detected on this date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Statistics",
                "verbose_name_plural": "Daily Statistics",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(fields=("date",), name="unique_date")
                ],
            },
        ),
    ]
