# Generated by Django 5.2.10 on 2026-01-21 09:06
# Modified to only add event_id field (person fields already exist from migration 0003)

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_person_cover_face_image_person_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Event ID from frontend (e.g., 'evt_1234567890')",
                max_length=100,
                null=True,
            ),
        ),
    ]
