# Generated by Django 5.2.10 on 2026-01-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_person_cover_face_image_person_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="When background processing completed", null=True
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="completed",
                help_text="Processing status: pending, processing, completed, failed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail_medium",
            field=models.CharField(
                blank=True,
                help_text="800x800 thumbnail for detail page",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail_small",
            field=models.CharField(
                blank=True,
                help_text="200x200 thumbnail for collections page",
                max_length=500,
                null=True,
            ),
        ),
    ]
