# Generated by Django 5.2.10 on 2026-01-22 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_person_cover_face_image_person_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personphoto',
            options={'ordering': ['-confidence', '-created_at'], 'verbose_name': 'Person Photo', 'verbose_name_plural': 'Person Photos'},
        ),
        migrations.AddField(
            model_name='personphoto',
            name='confidence',
            field=models.FloatField(db_index=True, default=0.0, help_text='Face detection confidence score (0.0-1.0). Higher = better quality.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
