# Generated by Django 4.2.16 on 2026-02-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_drivelink_to_folderpath'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledjob',
            new_name='api_schedul_schedul_3c2cc3_idx',
            old_name='api_schedul_schedul_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledjob',
            new_name='api_schedul_is_acti_fa15e7_idx',
            old_name='api_schedul_is_acti_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='cover_face_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cover_image_quality_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='person',
            name='face_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
