# Generated by Django 4.2.16 on 2026-02-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_api_schedul_schedul_idx_api_schedul_schedul_3c2cc3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personphoto',
            name='face_bbox',
            field=models.JSONField(blank=True, help_text='Bounding box {x, y, width, height} of face in photo', null=True),
        ),
        migrations.AddField(
            model_name='personphoto',
            name='face_embedding',
            field=models.JSONField(blank=True, help_text='512D face embedding vector for this specific face detection', null=True),
        ),
    ]
